-- Users
CREATE TABLE IF NOT EXISTS rezeptbuch_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    administrator BOOLEAN DEFAULT FALSE,
    deleted BOOLEAN DEFAULT FALSE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Categories
CREATE TABLE IF NOT EXISTS rezeptbuch_categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Recipes
CREATE TABLE IF NOT EXISTS rezeptbuch_recipes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ingredients LONGTEXT NOT NULL,
    description LONGTEXT NOT NULL,
    creator INT UNSIGNED NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (creator) REFERENCES rezeptbuch_users (id)
);

-- Recipe Category Assignments
CREATE TABLE IF NOT EXISTS rezeptbuch_recipe_category_assignments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recipe INT UNSIGNED NOT NULL,
    category INT UNSIGNED NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (recipe) REFERENCES rezeptbuch_recipes (id),
    FOREIGN KEY (category) REFERENCES rezeptbuch_categories (id)
);